### ISSUE TITLE
"github.com/influxdata/influxdb/v2/pkg/escape" doesn't exists

### ISSUE THREAD

**Issue by sankarr-technitto** [rvolosatovs/influx-taggify#2]
trying to download influx-taggify using 

GO111MODULE=off go get -u github.com/rvolosatovs/influx-taggify

i am getting following error,
code in directory /home/pi/go/src/github.com/influxdata/influxdb/pkg/escape expects import "github.com/influxdata/influxdb/v2/pkg/escape"

when i checked influxdb location in github, v2 doesn't exists anymore. I am struck an help

**Comment by rvolosatovs** [comment]
Thank you for the report @sankarr-technitto
It's been a while since I wrote this and used InfluxDB, so I cannot guarantee that the logic is still correct (e.g. if line protocol spec changed it might not be)
In any case, I added https://github.com/rvolosatovs/influx-taggify/commit/a9950e751563bf4b0c03777e94f13faa30ff4ea1
With this commit in place I was able to run the tool without issues on `go version go1.16.4 linux/amd64` (NOTE: you do not need `GO111MODULE=off` anymore)
